"""add dark mode

Revision ID: 190e633975d8
Revises: 833696944cb1
Create Date: 2022-01-05 14:33:30.654977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190e633975d8'
down_revision = '833696944cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dark_mode', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('dark_mode')

    # ### end Alembic commands ###
