"""add category banner

Revision ID: 833696944cb1
Revises: 918b604472d0
Create Date: 2022-01-03 11:16:47.234664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833696944cb1'
down_revision = '918b604472d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('banner')

    # ### end Alembic commands ###
