"""Add dislikes

Revision ID: 85876f52a7bf
Revises: f20086ba2aff
Create Date: 2021-12-26 16:30:45.960627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85876f52a7bf'
down_revision = 'f20086ba2aff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dislike',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('post_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dislike')
    # ### end Alembic commands ###
