"""add post media

Revision ID: 918b604472d0
Revises: db1312aff6a7
Create Date: 2022-01-02 23:51:59.923285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918b604472d0'
down_revision = 'db1312aff6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('media')

    # ### end Alembic commands ###
